name: Picooc ScaleConnect
version: "1.0.1"
slug: picooc_scaleconnect
description: SmartScaleConnect with mainland Picooc support

arch:
  - amd64
  - aarch64

startup: system
init: false
stdin: true

options:
  db: true
  db_path: ""
  sleep: 24h

schema:
  db: bool
  db_path: "str"
  sleep: "str"

map: [ "config:rw" ]
