name: Picooc ScaleConnect
version: "1.0.0"
slug: picooc_scaleconnect
description: SmartScaleConnect with mainland Picooc support

arch:
  - amd64
  - aarch64

startup: services
boot: auto

options:
  sleep: 24h

schema:
  sleep: str

map:
  - type: homeassistant_config
    path: /config
    read_only: false
